# ------------ Transformers' Arguments For CTR Task-------------------
train:
    output_dir: ./ctr
    num_train_epochs: 10
    lr_scheduler_type: reduce_lr_on_plateau
    per_device_train_batch_size: 512
    per_device_eval_batch_size: 512
    logging_strategy: epoch
    logging_nan_inf_filter: False
    save_strategy: epoch
    metric_for_best_model: auc
    greater_is_better: True
    evaluation_strategy: epoch
    prediction_loss_only: False
    load_best_model_at_end: True


user_bins: 1
item_bins: 7
do_infer: False
pretrained_dir: ~