# # ---------- Amazon ---------------
# ctr_model:
#     activation: dice
#     attention_mlp: [64, 32]
#     batch_norm: True
#     dropout: 0.0
#     fc_mlp: [128, 64, 64]

#     learning_rate: 3e-3
#     weight_decay: 3e-2

# # --------- MovieLens ----------
ctr_model:
    activation: dice
    attention_mlp: [64, 32]
    batch_norm: True
    dropout: 0.0
    fc_mlp: [128, 64, 64]

    learning_rate: 6e-3
    weight_decay: 5e-4

    text_embedding_path: ~