# ---------- Amazon ---------------
ctr_model:
    product_type: inner
    mlp_layer: [128, 64, 64]
    activation: relu
    dropout: 0.0
    batch_norm: True
    stack_dim: 3

    
    learning_rate: 5e-3
    weight_decay: 3e-2

# --------- MovieLens ----------
# ctr_model:
#     product_type: inner
#     mlp_layer: [128, 64, 64]
#     activation: relu
#     dropout: 0.0
#     batch_norm: True
#     stack_dim: 3

    
#     learning_rate: 8e-3
#     weight_decay: 8e-2