# ---------- Amazon ---------------
ctr_model:
    batch_norm: True
    mlp_layer: [128, 64, 64]
    activation: relu
    dropout: 0.0

    learning_rate: 3e-3
    weight_decay: 5e-2


# --------- MovieLens ----------
# ctr_model:
#     batch_norm: True
#     mlp_layer: [128, 64, 64]
#     activation: relu
#     dropout: 0.0

#     learning_rate: 7e-3
#     weight_decay: 5e-2